/**
 * @module EmployeeSchema
 * Comprehensive validation logic for Employee entities.
 * Handles creation, updates, and complex filtering with business rule enforcement.
 */

import { z } from "zod";
import { departmentSchema } from "./department.schema";
import { EMPLOYEES_CONFIG } from "@/config/employees-config";
import { nameSchema, dateStringSchema } from "./common";
import { calculateAge } from "@/utils/dateUtils";

const { salary, age } = EMPLOYEES_CONFIG;

/**
 * Core Employee Schema.
 * Includes custom age validation logic linked to global configuration limits.
 */
export const employeeSchema = z.object({
  id: z.string(),
  fullName: nameSchema,
  // Coerce is used to handle string inputs from forms as numbers
  salary: z.coerce.number()
    .min(salary.min, `Min salary: ${salary.min}`)
    .max(salary.max, `Max salary: ${salary.max}`),
  
  /**
   * Validates birthDate by calculating age and comparing against 
   * defined business limits (e.g., 20-65 years).
   */
  birthDate: dateStringSchema.refine((date) => {
    const currentAge = calculateAge(date);
    return currentAge >= age.min && currentAge <= age.max;
  }, {
    message: `Age must be between ${age.min} and ${age.max} years old`,
  }),

  department: departmentSchema,
  avatar: z.string().url().nullable().optional(),
});

/** Full Employee entity type */
export type Employee = z.infer<typeof employeeSchema>;

/**
 * Schema for creating a new employee.
 * Excludes 'id' as it is typically generated by the server/database.
 */
export const newEmployeeSchema = employeeSchema.omit({ id: true });
export type NewEmployee = z.infer<typeof newEmployeeSchema>;

/**
 * Schema for patch/update operations.
 * Requires an ID and allows partial updates for all other fields.
 */
export const employeeUpdateSchema = z.object({
  id: z.string(),
  changes: newEmployeeSchema.partial(),
});
export type EmployeeUpdatePayload = z.infer<typeof employeeUpdateSchema>;

/**
 * Configuration for the search/filter state.
 * Ensures consistent default values for the UI and Store.
 */
export const employeeFilterSchema = z.object({
  department: z.union([departmentSchema, z.literal("All")]).default("All"),
  minSalary: z.coerce.number().default(EMPLOYEES_CONFIG.salary.min),
  maxSalary: z.coerce.number().default(EMPLOYEES_CONFIG.salary.max),
  minAge: z.coerce.number().default(EMPLOYEES_CONFIG.age.min),
  maxAge: z.coerce.number().default(EMPLOYEES_CONFIG.age.max),
});

/** Type for employee filter parameters */
export type EmployeeFilter = z.infer<typeof employeeFilterSchema>;